repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: requirements-txt-fixer
    - id: check-merge-conflict
    - id: check-json
    - id: double-quote-string-fixer
    - id: check-ast
    - id: check-added-large-files
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.11.0
  hooks:
    - id: reorder-python-imports
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.290'
  hooks:
    - id: ruff
