version: '3'

services:
  postgres:
    image: postgres:12
    volumes:
      - "cookie-pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=cookie_local
      - POSTGRES_USER=cookie
      - POSTGRES_PASSWORD=cookie
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U cookie"
      interval: 300s
      timeout: 50s
      retries: 10
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: web
    build: ./
    command: >
      bash -c "./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  cookie-pgdata:
