version: '3'

services:
  "{{cookiecutter.github_repository_name}}":
    build: .
    image: "{{cookiecutter.github_repository_name}}:latest"
    volumes:
      - ".:/opt/{{cookiecutter.github_repository_name}}"
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    volumes:
      - "cookie-pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=cookie_local
      - POSTGRES_USER=cookie
      - POSTGRES_PASSWORD=cookie
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U cookie"
      interval: 300s
      timeout: 50s
      retries: 10

volumes:
  cookie-pgdata:
